import type { ParcoursItem } from "@/types/parcours";

export const parcoursContent = {
  eyebrow: "Parcours",
  title: {
    prefix: "Des expériences,",
    highlight: "un même fil conducteur.",
  },
  description: "Mon parcours n’est pas une succession d’expériences. C’est la construction progressive d’une même expertise : concevoir des produits utiles, résoudre des problèmes complexes et faire les bons choix techniques.",
  keywords: ["Evolution", "Expérience", "Conception"],
} as const;

export const parcoursItems = [
  {
    id: "novrh",
    period: "2025 — 2026",
    title: "Ingénieur logiciel · Data & automatisation",
    organization: "NovRH",
    location: "Aix-en-Provence",
    description: "Intervention sur des données clients complexes, création de traitements Node.js en masse et développement d’outils internes destinés à fiabiliser les tests et les opérations métier.",
    type: "experience",
    icon: "database",
    technologies: ["Node.js", "TypeScript", "SQL", "Cypress"],
    accent: "violet",
  },
  {
    id: "la-provence",
    period: "2023 — 2024",
    title: "Développeur backend",
    organization: "La Provence",
    location: "Marseille",
    description: "Développement de services backend et mise en place d’un système WebSocket destiné à synchroniser les données applicatives en temps réel.",
    type: "experience",
    icon: "radioTower",
    technologies: ["Node.js", "WebSocket", "API", "Event-driven"],
    accent: "cyan",
  },
  {
    id: "tree-digital-factory",
    period: "2020 — 2021",
    title: "Développeur full stack",
    organization: "Tree Digital Factory",
    description: "Développement d’outils d’administration et de tableaux de bord orientés données, avec participation à la mise en production de produits web complets.",
    type: "experience",
    icon: "braces",
    technologies: ["JavaScript", "Node.js", "Dashboards", "Data"],
    accent: "violet",
  },
  {
    id: "tickandbox",
    period: "2019 — 2020",
    title: "Développeur produit",
    organization: "TickAndBox",
    description: "Conception d’applications web et mobiles à partir de zéro, intégration de services externes et participation à l’ensemble du cycle de développement produit.",
    type: "experience",
    icon: "code",
    technologies: ["Web", "Mobile", "Paiement", "Géolocalisation"],
    accent: "indigo",
  },
  {
    id: "winamax",
    period: "2019",
    title: "Développeur logiciel",
    organization: "Winamax",
    description: "Travail sur des flux événementiels et réalisation de scripts de migration et de transformation de données dans un environnement technique hétérogène.",
    type: "experience",
    icon: "workflow",
    technologies: ["Node.js", "NestJS", "Symfony", "Data"],
    accent: "cyan",
  },
  {
    id: "enseirb-matmeca",
    period: "2015 — 2019",
    title: "Diplôme d’ingénieur en génie logiciel",
    organization: "ENSEIRB-MATMECA",
    location: "Bordeaux",
    description: "Formation d’ingénieur orientée développement logiciel, architecture des systèmes, algorithmique et conception d’applications complexes.",
    type: "education",
    icon: "graduation",
    technologies: ["Génie logiciel", "Algorithmique", "Architecture"],
    accent: "violet",
  },
  {
    id: "prepa-thiers",
    period: "2012 — 2015",
    title: "Classes préparatoires MPSI / MP",
    organization: "Lycée Thiers",
    location: "Marseille",
    description: "Formation intensive en mathématiques, physique et informatique préparant aux concours des grandes écoles d’ingénieurs.",
    type: "education",
    icon: "graduation",
    technologies: ["Mathématiques", "Physique", "Informatique"],
    accent: "indigo",
  },
] satisfies ParcoursItem[];